name: publish
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  test:
    name: Unit Test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout toolbox repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Initialize Toolbox
        run: npm run init
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_AUTH_TOKEN}}
      - name: Run test
        run: npm run test
  publish:
    name: Publish Packages
    if: github.event.pull_request.merged == true
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout toolbox
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Fetch all tags
        run: git fetch --all
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Initialize Toolbox
        run: npm run init
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_AUTH_TOKEN}}
      - name: Set up git user email
        run: git config --global user.email "abnerariel-1997@hotmail.com"
      - name: Set up git user name
        run: git config --global user.name "abnerey"
      - name: Pump affected packages version
        run: npm run version
      - name: Build affected packages
        run: npm run ci:build
      - name: Publish packages
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_AUTH_TOKEN}}


